# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
# You are expected to edit it rarely.
# Changes require a rebuild by GitHub Pages.

# Site settings
baseurl: ""  # site is served from the root (<username>.github.io)

title: Pablo Valenzuela
author: Pablo Valenzuela
position: Software Engineering Researcher
affiliation: University of Bern Â· Universidad de La Frontera
email: pablo at valenzuela [at] unibe.ch / ufrontera.cl

# Academic & professional profiles
scholar:
  url: https://scholar.google.com/citations?user=G701cJ4AAAAJ&hl=en

github:
  url: https://github.com/pavt

linkedin:
  url: https://www.linkedin.com/in/pablo-valenzuela-a26603330/

# Build settings
markdown: kramdown

plugins:
  - jekyll-email-protect

# Collections used by the theme
collections:
  - publications
  - news

