- category: Program Committees
  items:
    - "MSR Conference (2022) – Junior PC"
    - "FSE Conference (2024, 2025, 2026) – Second Reviewer"
    - "MSR4P&S (SANER) (2025) – PC"
    - "Technical Debt Conference (2026) – Junior PC"
    - "ICSME Conference (2025) – Second Reviewer"
    - "ICSE Conference (2025, 2026) – Second Reviewer"
    - "EASE Conference (2025) – Second Reviewer"
    - "SPLC Conference (2025) – Second Reviewer"
    - "Technical Debt Conference (2026) – Junior PC"
    - "FSE Conference (2026) – Tutorials PC"


- category: Journal Reviewer
  items:
    - "ACM Transactions on Software Engineering and Methodology"
    - "Journal of Software: Evolution and Process"

- category: Talks
  items:
    - "3rd International Software Engineering Summer School, Lugano, Switzerland (Sep 11–13, 2023) – Presented “A Moldable Approach for GitHub Actions Analysis”"
    - "AIware Leadership Bootcamp, Toronto, Canada (Nov 03–08, 2024) – Presented “Can LLMs Explain GitHub Action Failures? Preliminary Results”"
    - "Innoguard Winter School, Bern, Switzerland (Nov 27, 2024) – Presented “Explaining GitHub Actions Failures with Large Language Models”"